### ISSUE TITLE
Engineering format on UNIX-timestamp

### ISSUE THREAD

**Issue by SpangeJ** [fangq/jdata#2]
In Matlab, if I run:
`
timestamp        = datestr(now,'yyyy-mm-dd HH:MM:SS');   %Matlab time whole days since year 0

t1                      = datetime(timestamp) ;
t1.TimeZone     = 'Europe/Oslo';
timestamp        = posixtime(t1);
jsonencode(timestamp)
`
The result is '1.55895412E+9'
It would be verry nice to avoid the '+E9' at the end.
Any way to JSON-encode 1558954120?

**Comment by fangq** [comment]
hi @SpangeJ, did you try `savejson` from [JSONLab](https://github.com/fangq/jsonlab)? it outputs an integer instead of a floating point number

```
>> savejson('',timestamp)

ans =

[1559031757]
```

I am closing this ticket as it is not really a JData specification related issue. Feel free to reopen if I missed your point.
